export const ActionTypes = {
  // Set types
  SET_USERS: "SET_USERS",
  SET_USER: "SET_USER",
  SET_WORKERS: "SET_WORKERS",
  SET_CLIENTS: "sET_CLIENTS",
  SET_POSTS: "SET_POSTS",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_SKILLS: "SET_SKILLS",
  SET_SKILLS_CHILDREN: "SET_SKILLS_cHILDREN",
  SET_LOCATIONS: "SET_LOCATIONS",

  // Update types
  UPDATE_USERS: "UPDATE_USERS",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_POSTS: "UPDATE_POSTS",

  // Delete types
  DELETE_USER: "DELETE_USER",

  // Remove types
  REMOVE_USER: "REMOVE_USER",

  // FiLTER TYPES
  FILTER_WORKERS: "FILTER_WORKERS",
  FILTER_CLIENTS: "FILTER_CLIENTS",
};
