export const ActionTypes = {
  // Set types
  SET_USERS: "SET_USERS",
  SET_USER: "SET_USER",
  SET_WORKERS: "SET_WORKERS",
  SET_CLIENTS: "sET_CLIENTS",
  SET_POSTS: "SET_POSTS",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_SKILLS: "SET_SKILLS",
  SET_SKILLS_CHILDREN: "SET_SKILLS_CHILDREN",
  SET_LOCATIONS: "SET_LOCATIONS",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  SET_SEARCH_RESULT: "SET_SEARCH_RESULT",
  SET_RECOMMENDED_JOBS: "SET_RECOMMENDED_JOBS",
  SET_USER_PROJECTS: "SET_USER_PROJECTS",
  SET_WORKERS_COUNT: "SET_WORKERS_COUNT",
  SET_CLIENTS_COUNT: "SET_CLIENTS_COUNT",

  // Update types
  UPDATE_USERS: "UPDATE_USERS",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_POSTS: "UPDATE_POSTS",
  UPDATE_USER_PROJECTS: "UPDATE_USER_PROJECTS",
  UPDATE_WORKER: "UPADATE_WORKER",

  // Delete types
  DELETE_USER: "DELETE_USER",

  // Remove types
  REMOVE_USER: "REMOVE_USER",

  // FiLTER TYPES
  FILTER_WORKERS: "FILTER_WORKERS",
  FILTER_CLIENTS: "FILTER_CLIENTS",
};
