export const ActionTypes = {
  // Set types
  SET_USERS: "SET_USERS",
  SET_USER: "SET_USER",
  SET_WORKER: "SET_WORKER",
  SET_WORKERS: "SET_WORKERS",
  SET_CLIENT: "SET_CLIENT",
  SET_CLIENTS: "sET_CLIENTS",
  SET_POSTS: "SET_POSTS",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_SKILLS: "SET_SKILLS",

  
  // Update types
  UPDATE_USERS: "UPDATE_USERS",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_POSTS: "UPDATE_POSTS",

  // Delete types
  DELETE_USER: "DELETE_USER",

  // Remove types
  REMOVE_USER: "REMOVE_USER",
};
